<h3>NumPy nedir?</h3>
Diziler üzerinde matematiksel ve mantıksal işlem yapmamıza olanak sağlayan kütüphanedir.<br>"Numerical Python" ın kısaltmasıdır.

<h3>Neden NumPy?</h3>
<ol>
<li>Pek çok python kütüphanesi ile uyumlu.</li>
<li>Normal python listelerine göre çok daha hızlı.</li>
<li>Açık kaynak kodlu</li>


<h3>Nasıl Yüklenir?</h3>
<h4><strong>pip install numpy</strong><h4> yada <h4><strong>conda install numpy</strong></h4>

<h3>Kodumuzda kullanmak için ne yapmalıyız?</h3>

In [ ]:
import numpy as np

<h3>ndarray Nesnesi</h3>
<ul>
<li>N-boyutlu dizi yapısıdır.</li>
<li>Aynı türden verileri saklamak ve manipule etmek için kullanılır.</li>
<li> Verilere indeks yoluyla ulaşılır. İndeks değeri 0'dan başlar.
</ul>


<h3>0 boyutlu dizi (Scalar)<h3>

In [ ]:
a = np.array(6)
print(a)
print(type(a))

6
<class 'numpy.ndarray'>


<h3>1 boyutlu dizi<h3>

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6])                        # 1 boyutlu dizi
b = np.arange(1, 7)
c = np.linspace(1, 6, num=6, dtype=int)
print("a\n", a)
print("b\n",b)
print("c\n",c)
print(type(a))   # a değişkeninin türü
print("ndim\n",a.ndim)    # dizinin boyut sayısı
print("shape\n",a.shape)   # dizinin şekli
print("size\n",a.size)    # dizideki eleman sayısı
print("dtype\n",a.dtype)   # dizideki değerlerin türü


a
 [1 2 3 4 5 6]
b
 [1 2 3 4 5 6]
c
 [1 2 3 4 5 6]
<class 'numpy.ndarray'>
ndim
 1
shape
 (6,)
size
 6
dtype
 int64


<h3>1 Boyutlu dizi değerlerine erişim</h3>

In [ ]:
ilk_deger = a[0]
ikinci_deger = a[1]
son_deger = a[5]
son_deger_yontem2 = a[-1]
sondan_ikinci_deger = a[-2]
ilk_uc_deger = a[0:3]
cift_index = a[0::2]
print("ilk deger\n",ilk_deger)
print("ikinci deger\n",ikinci_deger)
print("son değer\n",son_deger)
print("son değer 2\n",son_deger_yontem2)
print("sondan 2. değer\n",sondan_ikinci_deger)
print("çift indeksteki değerler\n",cift_index)

ilk deger
 1
ikinci deger
 2
son değer
 6
son değer 2
 6
sondan 2. değer
 5
çift indeksteki değerler
 [1 3 5]


<h3>2 boyutlu dizi<h3>

In [ ]:
x = np.array([[3,5,7],
              [6,0,1],
              [6,7,4]])  # 2 boyutlu dizi
print("x\n", x)

a = np.array([[1,2,3], [4,5,6]])  # 2 boyutlu dizi
b = np.arange(1,7).reshape(2,3)   # tek boyuttan 2 boyuta
print("a\n",a)
print("b\n",b)

# tüm değereri 1 olan matris
birler = np.ones(shape=(3,4), dtype=float)
#tüm değerleri 0 olan matris
sifirlar = np.zeros(shape=(2,2), dtype=int)
# 5 e 5 lik birim matris I
birim_matris = np.eye(5)
# matrisi belli bir değerle doldurma
ayni_degerler = np.full(shape=(5,5), fill_value=9)
print("birler\n",birler)
print("sıfırlar\n",sifirlar)
print("birim matris\n",birim_matris)
print("aynı değerle doldurma\n",ayni_degerler)

bos_degerler = np.empty((3,6), dtype=np.uint8)
print("boş değerler\n",bos_degerler)
bos_degerler.fill(6)
print("doldurulan değerler\n",bos_degerler)


x
 [[3 5 7]
 [6 0 1]
 [6 7 4]]
a
 [[1 2 3]
 [4 5 6]]
b
 [[1 2 3]
 [4 5 6]]
birler
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
sıfırlar
 [[0 0]
 [0 0]]
birim matris
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
aynı değerle doldurma
 [[9 9 9 9 9]
 [9 9 9 9 9]
 [9 9 9 9 9]
 [9 9 9 9 9]
 [9 9 9 9 9]]
boş değerler
 [[7 7 7 7 7 7]
 [7 7 7 7 7 7]
 [7 7 7 7 7 7]]
doldurulan değerler
 [[6 6 6 6 6 6]
 [6 6 6 6 6 6]
 [6 6 6 6 6 6]]


<h3> 2 boyutlu dizilerde verilere erişim</h3>

In [ ]:
a = np.array([[1,2,3], [4,5,6]])  # 2 boyutlu dizi
print("1.satır 1.sütun\n",a[0,0])   # matriste 1.satır 1.sütundaki değer
print("2.satır 3.sütun\n",a[1,2])   # matriste 2.satır 3.sütundaki değer

1.satır 1.sütun
 1
2.satır 3.sütun
 6


<h3>Dilimleme</h3>

In [ ]:
a = np.array([[1,2,3,4], [4,5,6,7], [7,8,9,10]])  # 2 boyutlu dizi
print("a\n", a)
# son 2 sütundaki degerler
print(a[:, 2:4])
print(a[:, -2:])
print(a[1:, 1:3])
print("1.satır\n", a[0, :])       # 1.satırdaki tüm değerler   a[0] ile aynı sonuç
print("1.sütun\n", a[:, 0])       # 1.sütundaki tüm değerler
print("ilk 2 satır\n", a[0:2, :]) # 1. ve 2.satırdaki tüm değerler
print("ilk 2 sütun\n", a[:, 0:2]) # 1. ve 2.sütundaki tüm değerler
# 2.satırdan 3.satıra, 2.sütundan 3.sütuna tüm değerler
print("2.ve 3. satır, 3.ve 4.sütun \n", a[1:3, 2:4])


a
 [[ 1  2  3  4]
 [ 4  5  6  7]
 [ 7  8  9 10]]
[[ 3  4]
 [ 6  7]
 [ 9 10]]
[[ 3  4]
 [ 6  7]
 [ 9 10]]
[[5 6]
 [8 9]]
1.satır
 [1 2 3 4]
1.sütun
 [1 4 7]
ilk 2 satır
 [[1 2 3 4]
 [4 5 6 7]]
ilk 2 sütun
 [[1 2]
 [4 5]
 [7 8]]
2.ve 3. satır, 3.ve 4.sütun 
 [[ 6  7]
 [ 9 10]]


<h3> Rassal Sayılar</h3>

In [ ]:
# 2 ile 6 arasında 12 tane sayı üret. 6 dahil değil.
a = np.random.randint(low=2, high=6, size=(3,4))
# normal dağılıma uyan 5 tane sayı üret.
b = np.random.randn(5)
# ortalaması 30, standart sapması 2 olan sayılar üret
c = np.random.normal(30, 2, size=(3,3)).astype(float)
print("a\n", a)
print("b\n", b)
print("c\n", c)

a
 [[3 2 2 4]
 [2 5 4 3]
 [4 4 3 5]]
b
 [ 0.86940631  1.55014003  0.27589222  1.07167643 -0.3730618 ]
c
 [[30.71861355 27.279988   30.16399066]
 [27.834377   30.78778387 31.80185624]
 [28.5134531  31.39502333 27.4699423 ]]


<h3> Aritmetik İşlemler</h3>

In [ ]:
x = np.eye(3)
y = np.arange(1,10).reshape(3,3)
print("x\n", x)
print("y\n", y)
print("x+y\n", x+y)
print("x*y\n", x*y)      # karşılıklı eleemanları çarp
print("x-y\n", x-y)
print("x/y\n", x/y)
print("x%y\n", x%y)      # mod
print("x**y\n", x**y)     # üs

x
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
y
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
x+y
 [[ 2.  2.  3.]
 [ 4.  6.  6.]
 [ 7.  8. 10.]]
x*y
 [[1. 0. 0.]
 [0. 5. 0.]
 [0. 0. 9.]]
x-y
 [[ 0. -2. -3.]
 [-4. -4. -6.]
 [-7. -8. -8.]]
x/y
 [[1.         0.         0.        ]
 [0.         0.2        0.        ]
 [0.         0.         0.11111111]]
x%y
 [[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
x**y
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


<h3>Lineer Cebir İşlemleri</h3>

In [ ]:
x = np.array([1,2,3,4,5,60])
y = np.array([5,6,7,8,9,10])
print("y-5\n", y-5)               # tüm değerlerden 5 çıkar
print("x*2\n", x*2)               # tüm değerleri 2 ile çarp
print("x**2\n", x**2)              # tüm değerlerin karesini al
print("sin(x)\n", np.sin(x))         # tüm değerlerin sinüsünü al
print("e^x\n", np.exp(x))         # tüm değerlerin e^x den geçir

z = np.dot(x,y)          # iç çarpım (dot product)
print("x.y\n", z)
x = y.reshape(3,2)       # 3x2 lik hale getir
y = y.reshape(2,3)       # 2x3 lik hale getir
print("x\n", x)
print("y\n", y)
print("yT", y.T)               # transpoz işlemi
print("x matmul y \n", np.matmul(x,y))    # matris çarpımı


y-5
 [0 1 2 3 4 5]
x*2
 [  2   4   6   8  10 120]
x**2
 [   1    4    9   16   25 3600]
sin(x)
 [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.30481062]
e^x
 [2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 1.14200739e+26]
x.y
 715
x
 [[ 5  6]
 [ 7  8]
 [ 9 10]]
y
 [[ 5  6  7]
 [ 8  9 10]]
yT [[ 5  8]
 [ 6  9]
 [ 7 10]]
x matmul y 
 [[ 73  84  95]
 [ 99 114 129]
 [125 144 163]]


<h3> Toplam Fonksiyonları</h3>

In [ ]:
x = np.arange(1,6)
x[2] = 1            # 3.degeri 1 yap
print(x)
print("toplam\n", np.sum(x))
print("ortalama\n", np.mean(x))
print("max\n", np.max(x))
print("maksimumun indeksi\n", np.argmax(x))
print("median\n", np.median(x))
print("eşsiz değerler\n", np.unique(x))


[1 2 1 4 5]
toplam
 13
ortalama
 2.6
max
 5
maksimumun indeksi
 4
median
 2.0
eşsiz değerler
 [1 2 4 5]


<h3>Belli bir eksende Toplam Fonksiyonları</h3>

In [ ]:
a = np.arange(1,7).reshape(2,3)
print("a\n", a)
x = np.sum(a, axis=0)    # satırları üst üste koy topla
y = np.sum(a, axis=1)    # her satırdaki tüm değerleri topla
print("axis=0 toplam\n", x)
print("axis=1 toplam\n", y)

a
 [[1 2 3]
 [4 5 6]]
axis=0 toplam
 [5 7 9]
axis=1 toplam
 [ 6 15]


<h3>Mantıksal Operatörler</h3>

In [ ]:
a = np.arange(1,7).reshape(2,3)
print("a\n",         a)
print("a>5\n",       a>5)  # 5 ten büyük olup olmama
print("a[a>5]\n",    a[a>5])           # 5 ten büyük olan değerleri getir
print("a%2== 0\n",   a%2 ==0)         # çift sayı mı
print("where a>2\n", np.where(a>2)) # hangi indeksteki değerler 2 den büyük
print("all(a)\n",    np.all(a))        # tüm değerler 0 dan ve False tan farklı mı
print("all a>1\n",   np.all(a>1))     # tüm değerler 1 den büyük mi ?
print("any(a)\n",    np.any(a))     # 0 dan ve False dan farklı değer var mı ?
sifirlar = np.zeros((3,3))
print("any sıfırlar\n", np.any(sifirlar))     # 0 dan ve False dan farklı değer var mı ?
print("any a>8\n",      np.any(a>8))          # 8 den büyük bir değer var mı ?

a
 [[1 2 3]
 [4 5 6]]
a>5
 [[False False False]
 [False False  True]]
a[a>5]
 [6]
a%2== 0
 [[False  True False]
 [ True False  True]]
where a>2
 (array([0, 1, 1, 1]), array([2, 0, 1, 2]))
all(a)
 True
all a>1
 False
any(a)
 True
any sıfırlar
 False
any a>8
 False


<h3>İki diziyi birleştirme</h3>

In [ ]:
a = np.arange(1,7).reshape(2,3)
b = np.random.randint(7, size=(2,3))
print("a\n", a)
print("b\n", b)
print("üst üste koy\n", np.vstack([a,b]))
print("yan yana koy\n", np.hstack([a,b]))

a
 [[1 2 3]
 [4 5 6]]
b
 [[6 4 0]
 [6 1 6]]
üst üste koy
 [[1 2 3]
 [4 5 6]
 [6 4 0]
 [6 1 6]]
yan yana koy
 [[1 2 3 6 4 0]
 [4 5 6 6 1 6]]


<h3>Dosya İşlemleri</h3>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

dosya = "/content/drive/My Drive/myo_yapay_zeka/sayisal_veri.csv"
veri = np.loadtxt(dosya, delimiter=",", skiprows=0)
veri

Mounted at /content/drive


array([[ 4.,  5.,  6.,  1.],
       [ 2.,  3.,  2.,  3.],
       [ 6., -5., -7., -1.]])

In [ ]:
ortalama = np.mean(veri, axis=0)
print(ortalama)
maks = np.max(veri, axis=0)
veri = (veri - ortalama)

[4.         1.         0.33333333 1.        ]


In [ ]:
veri = veri/ maks
veri

array([[ 0.        ,  0.8       ,  0.94444444,  0.        ],
       [-0.33333333,  0.4       ,  0.27777778,  0.66666667],
       [ 0.33333333, -1.2       , -1.22222222, -0.66666667]])

In [ ]:
np.savetxt('islenmis_sayisal_veri.csv', veri, delimiter=',')